main: u4.c linkedlist.c
	gcc -o main u4.c linkedlist.c

.PHONY: program 

program: main
	main

test: test.c linkedlist.c
	gcc -o test test.c linkedlist.c

.PHONY: testavimas 

testavimas: test
	test